### ISSUE TITLE
Add linter 

### ISSUE THREAD

**Issue by victormanuelfrancodev** [the-d-velopers/animated_book_widget#7]
**Description:** 
A linter enforces a consistent coding style across the project. This is especially important in team environments, where multiple developers contribute to the same codebase. Consistency makes the code more readable and maintainable.
Linters can catch potential errors and bad practices early in the development process. By identifying issues like syntax errors, unused variables, or deprecated APIs, they help in preventing bugs that might be harder to diagnose later.

**Task:** 
Research the best Flutter linters currently available and add one to the project.

**Comment by diegoveloper** [comment]
very_good_analysis was added on this PR : https://github.com/the-d-velopers/animated_book_list/pulls , should we choose a different one?

**Comment by victormanuelfrancodev** [comment]
@diegoveloper It's true!, I didn't see that. let me delete the issue 

```
 very_good_analysis:
    dependency: "direct dev"
    description:
      name: very_good_analysis
      sha256: "9ae7f3a3bd5764fb021b335ca28a34f040cd0ab6eec00a1b213b445dae58a4b8"
      url: "https://pub.dev"
    source: hosted
    version: "5.1.0"
    ```
